### PR TITLE
Openbabel recipe

### PR DESCRIPTION
**Pull request by rwest**
Still not fully working.

### CODE REVIEW

**Comment by rwest** [comment]
See https://github.com/conda/conda-recipes/issues/309 for discussion of how to set or avoid the need to set `$BABEL_LIBDIR` and `$BABEL_DATADIR`

**Comment by rwest** [comment]
This is now working for me, on Mac OS X

**Comment by rwest** [comment]
See also https://github.com/conda/conda-recipes/pull/310 where more people will be commenting and contributing.

**Comment by connie** [comment]
The only difference I have now for the linux build is 

```
-      -DPYTHON_LIBRARY=$PREFIX/lib/libpython$PY_VER.dylib \
+      -DPYTHON_LIBRARY=$PREFIX/lib/libpython$PY_VER.so \
```

Is there a quick fix for detecting shared library ending differences between osx and linux?

**Pull request merged**
