### PR TITLE
Complete `conda-recipes` Overhaul

### PR DESCRIPTION
**Pull request by JacksonBurns**
### Add GitHub Actions
GitHub provides free runners that can build these for us, so this PR will add those!
Specifically, we will build on all platforms and (eventually) all versions of Python that we want to support.

### Technical Debt Cleanup
Many of the recipes in this repository are no longer needed since we now use the official builds, so this PR will remove them.

Here's the fate of all of the recipes:
 - now on conda-forge/official, removed: gprof2dot, quantities, pyjulia, pydot, openbabel, mopac, julia, coolprop, cclib, cairo, cairocffi, lpsolve55, pyrdl
 - unused, removed: zmats (was originally used for ARC), scoop, py3dmol, py2cairo, pixman, lpsolve, guppy, fontconfig, eigen, pyrms, diffeqpy
 - sticking around, but just removed the windows stuff we don't use: symmetry

### Status of remaining packages:
 - symmetry: works on all platforms!

### CODE REVIEW

**Comment by JacksonBurns** [comment]
Python 3.7 has not been backported to M1 hardware with conda binaries, so those package builds will never run. We will have to hold off on M1 binaries until after the Python version upgrade.

**Comment by JacksonBurns** [comment]
So the patches to the `lpsolve` recipe aren't working. It appears that both the tool itself as well as the python 3 compatible wrappers have been abandoned.

I think we should seriously consider just using a different linear solver. [Scipy has some great options](https://docs.scipy.org/doc/scipy-1.12.0/reference/generated/scipy.optimize.linprog.html) these days, so this approach we are doing is probably no longer required.

Update: removal of lpsolve55 usage in RMG is ongoing, see this comment: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2671#issuecomment-2168498896

**Comment by JacksonBurns** [comment]
The `pyrdl` failure is annoying to diagnose on GitHub actions. During the build process we generate a `Makefile`, which we later use to run `make test` - I can't actually see what it's doing, only that it attempts to change to a directory which does not exist. This will need to be debugged locally.

Of note is that the package does actually seem to build correctly. The `import py_rdl` works, it's just that the tests don't.

**Comment by JacksonBurns** [comment]
Turns out someone actually already maintains an `lpsolve55` recipe (https://github.com/conda-forge/lpsolve55-feedstock) so I am working on a PR on RMG to use that instead (https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2680). If that's successful, I am just going to delete `lpsolve55` from this repo.

**Comment by JacksonBurns** [comment]
Ha so there is also a `ringdecomposerlib-python` binary on `conda-forge` as well - also trying that in RMG now: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2681

**Comment by JacksonBurns** [comment]
Especially since there are now only going to be a couple recipes here - could we bring back windows support?

**Comment by JacksonBurns** [comment]
@hwpang @rwest this PR is ready now. We need to update the anaconda token on this repo (I will do this) and create a stable branch to merge into to trigger the builds and uploads (I will do this as well). Please let me know how the changes look!

**Review by rwest — APPROVED** [review]
Looks ok. I'm fine with removing the old stuff.  Will this do multiple Python versions? Do we want it to?

**Comment by JacksonBurns** [comment]
Symmetry actually doesn't depend on Python. It is compatible with all versions of Python, in that way. There are no Python recipes left in this repo.

**Review by hwpang — APPROVED** [review]
LGTM too

**Pull request merged**
