### PR TITLE
Added zmats 0.1.0

### PR DESCRIPTION
**Pull request by alongd**
Added a Z matrix module for manipulating molecular internal coordinates.
Code taken from [ARC](https://github.com/ReactionMechanismGenerator/ARC).

### CODE REVIEW

**Comment by alongd** [comment]
@amarkpayne, I'm inexperienced in packaging, please let me know if everything seems OK.
Is by adding a package to this repo the command `conda install -c rmg zmats` will function automatically as expected, or do I need to make conda somehow aware of a new package?
Thanks!

**Comment by amarkpayne** [comment]
@alongd I am taking a look at this PR now. This repository just stores the recipes that can be used to build the packages on any computer. For `conda install -c rmg zmats` to work the built package needs to be uploaded to the RMG channel on Anaconda Cloud.

Since reviewing this PR will require me building this package locally anyways, I'll go ahead and upload this package for you after I build on my PC. 

Note that you can also create your own personal Anaconda Cloud channel to upload packages to. For example, this can be a convenient first step to test that everything went okay with the build process. It can also be useful if you have packages for your own project outside of RMG.

**Comment by amarkpayne** [comment]
@alongd I have just forced pushed some changes (to rebase onto current master after I merged in a PR). I kept your original commit, and included all of my changes in the fixup commit. Specifically, my changes do the following things:

1. Instead of having to rely on PIP and uploading the package to PyPI, the recipe now gets the package directly from GitHub.

2. I added a `noarch: generic` flag so that this build works for all operating systems (since this appears to be an all-python package. correct me if I am wrong). This saves us time from having to create separate builds for each OS.

3. I added all of the run-time dependencies to the conda recipe, which are need for the build to work.


I was able to build this package successfully on my local machine by running `conda-build ./ --python 3.7 -c rmg -c rdkit -c cantera -c pytorch -c conda-forge`. I have since uploaded this package to the RMG Anaconda Cloud channel. Let me know if you are able to install and use this package (i.e. `conda install -c rmg zmats` should work now, though if RMG is not already in the existing environment you'll need to use `conda install -c rmg -c rdkit -c cantera -c pytorch -c conda-forge zmats` so that conda can find all of RMG's dependencies).

**Let me know if these changes look okay to you**. If so go ahead and squash the fixup and I'll merge this in. Thanks for the PR!

**Comment by amarkpayne** [comment]
One final comment: because this package depends on RMG-Py, we need to be careful where it gets used. For example, this should never be used in RMG-Py itself. Using it for ARC or AutoTST for example is fine, since they already have RMG-Py as a conda dependency.

**Comment by alongd** [comment]
Thanks for the assistance, @amarkpayne!
It all looks good - I squashed the fixup commit.

**Review by amarkpayne — APPROVED** [review]

**Pull request merged**
